# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install -e ".[docs]"
    - cd docs && make html

# Python requirements
python:
  install:
    - requirements: docs/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
  builder: html

# Build PDF output
formats:
  - pdf

# Submodules (if any)
submodules:
  include: all
  recursive: true
